language: php
sudo: false

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: nightly

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --exclude-group=IntegrationTest --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml ./tests
  - ./vendor/bin/phpcs --standard=PSR2 src

after_script:
  - php vendor/bin/coveralls -v
